version: '3.5'

services:
  fx-service:
    build: .
    image: smax/fx-service:latest
    container_name: "fx-service"
    ports:
      - "8080:8080"
    depends_on: 
      - "currencies-db"
  currencies-db:
    image: postgres:11.2-alpine
    container_name: "currencies-db"
    volumes:
      - currencies-db:/var/lib/postgresql/data
      - ./app/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  currencies-db:
    name: currencies-db

# networks:
#   fx:
#     name: fx
#     driver: bridge

networks:
  default:
    external:
      name: fx
